<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Execute_ClientAssertion_Generator_Request">
        <xs:annotation>
            <xs:documentation>Execute_ClientAssertion_Generator Input Operation
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="1" name="url"
                            type="xs:normalizedString">
                    <xs:annotation>
                        <xs:appinfo>
                            <rest:metadata indexed="true" required="true"
                                           xmlns:rest="uri:com.boomi.rest" />
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element maxOccurs="1" minOccurs="1" name="auth_code"
                            type="xs:normalizedString">
                    <xs:annotation>
                        <xs:appinfo>
                            <rest:metadata indexed="true" required="true"
                                           xmlns:rest="uri:com.boomi.rest" />
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element maxOccurs="1" minOccurs="0" name="client_id"
                            type="xs:normalizedString">
                    <xs:annotation>
                        <xs:appinfo>
                            <rest:metadata indexed="true" xmlns:rest="uri:com.boomi.rest" />
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element maxOccurs="1" minOccurs="0" name="jwks_json"
                            type="xs:normalizedString">
                    <xs:annotation>
                        <xs:appinfo>
                            <rest:metadata indexed="true" xmlns:rest="uri:com.boomi.rest" />
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>